---
name: Code Coverage
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  code_coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: npm install
      - run: npm run coverage
      - uses: actions/upload-artifact@v2
        with:
          name: master-codecov
          path: coverage/coverage-summary.json
      - uses: actions/checkout@v2
      - run: npm install
      - uses: actions/download-artifact@v2
        with:
          name: master-codecov
      - shell: bash
        run: |
          mkdir master
          mv coverage-summary.json master
      - run: npm run coverage
      - id: set_var
        run: |
          content=`cat coverage/coverage-summary.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=actualcodecov::$content"
      - run: |
          export actualcov="${{fromJson(steps.set_var.outputs.actualcodecov).total.statements.pct}}"
      - run: echo $actualcov
