---
name: Code Coverage
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  code_coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: npm install
      - run: npm run coverage
      - uses: actions/upload-artifact@v2
        with:
          name: master-codecov
          path: coverage/coverage-summary.json
      - uses: actions/checkout@v2
      - run: npm install
      - uses: actions/download-artifact@v2
        with:
          name: master-codecov
      - shell: bash
        run: |
          mkdir master
          mv coverage-summary.json master
      - run: npm run coverage
      - run: npm install json
      - shell: bash
        run: |
          export actualcodecov=$(cat master/coverage-summary.json | json total.statements.pct)
          echo $actualcodecov