---
name: Code Coverage
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  code_coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: npm install
      - run: npm run coverage
      - uses: actions/upload-artifact@v2
        with:
          name: master-codecov
          path: coverage/coverage-summary.json
      - uses: actions/checkout@v2
      - run: npm install
      - uses: actions/download-artifact@v2
        with:
          name: master-codecov
      - shell: bash
        run: |
          mkdir master
          mv coverage-summary.json master
      - run: npm run coverage
      - id: set_actualcov
        run: |
          content=`cat coverage/coverage-summary.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=actualcodecov::$content"
      - id: set_mastercov
        run: |
          content=`cat master/coverage-summary.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=mastercodecov::$content"
      - id: set_codecovmsg
        run: |
          actualcov="${{fromJson(steps.set_actualcov.outputs.actualcodecov).total.statements.pct}}"
          mastercov="${{fromJson(steps.set_mastercov.outputs.mastercodecov).total.statements.pct}}"
          if [ "$actualcov" -gt "$mastercov" ]; then covmsg="Actual code coverage is ${actualcov}"
          echo "::set-output name=covmsg::$covmsg"
      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ${{fromJson(steps.set_codecovmsg.outputs.covmsg)}}
            })
          
